name: 'Diff Airflow DAG'
description: 'Gets diff of airflow DAG.'
inputs:
  base-image:
    description: 'Docker base image'
    required: false
    default: 'apache/airflow:1.10.10-python3.7'
outputs:
  diff:
    description: 'The diff of the DAGs.'
    value: ${{ steps.run.outputs.diff }}
runs:
  using: 'composite'
  steps:
    - id: run
      run: |
        cd ${{ github.action_path }}
        docker build . --build-arg BASE_IMAGE=${{ inputs.base-image }} -t airflow-diff-image
        env > /tmp/env
        docker run --rm -v ${{ github.workspace }}:${{ github.workspace }} --workdir ${{ github.workspace }} --env-file /tmp/env airflow-diff-image
      shell: bash
